// Generated by Selenium IDE
//import org.junit.Test;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
public class UserRemuvalTest extends TestBase {

  @Test
  public void testDelete() {

    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    driver.findElement(By.linkText("home")).click();
    driver.findElement(By.name("selected[]")).click();
    driver.findElement(By.cssSelector(".left:nth-child(8) > input")).click();
    driver.findElement(By.linkText("home")).click();
  }
}
